### ISSUE TITLE
크롬에서 새로운글 갱신 안됨

### ISSUE THREAD

**Issue by taehoon6693** [koolside/koolside#12]
webfont.js:16 Mixed Content: The page at 'https://gall.dcinside.com/mgallery/board/lists?id=furry' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Nanum+Gothic:700,400&subset=latin,cyrillic,latin-ext,cyrillic-ext,vietnamese,greek-ext,greek'. This request has been blocked; the content must be served over HTTPS.
u @ webfont.js:16
koolside.user.js:31 https://m.dcinside.com/board/furry?notice=0&recommend=0
koolside.user.js:31 https://m.dcinside.com/board/furry/397443
koolside.user.js:31 https://m.dcinside.com/board/furry/397444
koolside.user.js:31 https://m.dcinside.com/board/furry?notice=0&recommend=0
koolside.user.js:31 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at k (koolside.user.js:31)
    at koolside.user.js:31
about:srcdoc:1 Mixed Content: The page at 'https://gall.dcinside.com/mgallery/board/lists?id=furry' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Nanum+Gothic:700,400&subset=latin,cyrillic,latin-ext,cyrillic-ext,vietnamese,greek-ext,greek'. This request has been blocked; the content must be served over HTTPS.

크롬 버전: 79.0.3945.88
확장프로그램:violentmonkey

**Comment by toriato** [comment]
https://github.com/toriato/koolside/blob/7cfd5c696efb841dfcbc4dc1b08a141c1fd57838/src/includes/gallery.ts#L373

대충 여기서 발생하는 오류 같은데 날짜를 정상적으로 파싱하지 못해서 발생하는 오류 같음
페이지 새로 고쳐도 못 불러옴?

**Comment by taehoon6693** [comment]
어제 점심까지만 해도 새로고침하면 해결됐는데 오늘 새벽즈음부터 새로고침해도 갱신안됨
