### ISSUE TITLE
기능 요청 및 버그

### ISSUE THREAD

**Issue by skotlex** [koolside/koolside#21]
~어떤 기능을 추가했으면 좋겠는지 작성해주세요, 터무니 없는 기능도 일단 올려보세요~

1. 개념글 버튼 눌러서 글 하나 클릭하고 하단에 리스트 보면 개념글 목록이 아니라 전체목록(일반게시글)이 나옴
2. 공지 숨기는게 디폴트 인거 같은데 공지 볼 수 있게 선택사항이 있었으면 좋겠음.

**Comment by skotlex** [comment]
3. 요소->갤러리->정보 클릭하면 최근방문갤러리까지 같이 숨김처리됨

**Comment by skotlex** [comment]
4. 아래 두 스샷 영역도 숨김처리 할 수 있었으면 좋겠음
4-1)
![주석 2020-01-11 022826](https://user-images.githubusercontent.com/31692408/72173077-1daea400-341a-11ea-9287-589b3e63683f.png)
4-2)
![주석 2020-01-11 022838](https://user-images.githubusercontent.com/31692408/72173084-20a99480-341a-11ea-9cc5-5a6950846291.png)

좋은 프로그램 감사합니다

**Comment by toriato** [comment]
- [x] 게시글 선택했을 때 기존 인자가 같이 넘어가지 않는 오류
- [ ] 공지 게시글이 보이지 않는 오류
- [x] 갤러리 정보 숨길 시 기록이 같이 숨겨지는 오류
- [x] 머리말과 꼬리말 요소 숨기는 기능
