### ISSUE TITLE
글목록에서 새 탭에서 열기 사용 불가

### ISSUE THREAD

**Issue by lekakid** [koolside/koolside#25]
글목록에서 우클릭 후 새 탭에서 열기 사용
id값으로 'https:'만 들어가는 것으로 보임
https://gall.dcinside.com/board/lists/?id=https:

오류 메세지는 따로 안 떴음

3.8.0 최신 기준

## 기기 정보
- 브라우저 이름: Whale(Chromium)
- 브라우저 버전: 2.6.90.16
- 사용 중인 확장 기능: Violentmonkey

**Comment by SlimeySlime** [comment]
새탭으로 열기 시에 url이 
https://gall.dcinside.com/https://gall.dcinside.com/mgallery/board/view?id=aoegame&no=10791428
형식으로 전달되네요.
앞에 https://gall.dcinside.com/ 부분을 제거하면 정상적으로 작동할 것 같아요

**Comment by toriato** [comment]
https://github.com/koolside/koolside/commit/00d6f7e6911b98d5c5b250b7da2f6ef72d36119d

해당 커밋에서 수정된 버그입니다
