### ISSUE TITLE
AdGuard와 충돌(추정)

### ISSUE THREAD

**Issue by khke1217** [koolside/koolside#26]
파이어폭스 환경에서 AdGuard가 활성화 된 상태에서 Violentmonkey로 확장프로그램을 로드할 경우 변경한 설정을 무시하고 기본 설정으로 동작함 (변경한 설정 자체는 남아있음)
AdGuard 자체 유저 스크립트 기능으로 확장프로그램을 로드할 경우 역시 마찬가지로 기본 설정으로 동작함
AdGuard 자체 유저 스크립트 기능의 설정 저장소가 갱신되지 않음

AdGuard 설정 저장소 내용 첨부
`{"caches":"[LString;[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]","config":"[LString;[object Object]"}`

**Comment by toriato** [comment]
https://greasyfork.org/ko/scripts/394469-koolside
0.3.17 에서 고쳤습니다, 업데이트해주시고 정상적으로 작동한다면 이슈 닫아주세요

**Comment by toriato** [comment]
파이퍼폭스랑 Adguard, Violentmonkey, koolside 버전 올려주실 수 있나요?
제가 테스트 했을 땐 이상 없었습니다.
- 파이어폭스 72.0.2 (메뉴 > 도움말 > Firefox 정보)
- Adguard 3.3.8 (설정 > 정보)
- Violentmonkey 2.12.4 (대시보드 > 정보)
- koolside 0.3.17 (대시보드 > 설치된 스크립트 > koolside 우측 정보란)

**Comment by khke1217** [comment]
koolside 0.3.16에서 0.3.17로 업데이트 한 뒤 정상적으로 작동 확인하였습니다.
