### ISSUE TITLE
예전에는 미리보기에서도 구글 이미지검색이나 다운로드 가능했던것같은데

### ISSUE THREAD

**Issue by fdsa1538** [koolside/koolside#27]
미리보기 키워놓고 우클릭해도 이미지 검색 메뉴가 안나오네요
삭제된 글에서 야짤 받는다고 막은거에요???
아님 나만 안돼요?

**Comment by toriato** [comment]
https://greasyfork.org/ko/scripts/394469-koolside
0.3.17 에서 고쳤습니다, 업데이트해주시고 정상적으로 작동한다면 이슈 닫아주세요

**Comment by fdsa1538** [comment]
저는 안고쳐졌어요..

**Comment by fdsa1538** [comment]
혹시나 싶어서 DIBE 확장프로그램 끄고 해봤는데 되네요!
DIBE 껐다가 켜서 koolside랑 같이 사용해보니 보니 될때도 있고 안될때도 있고 그러네요

**Comment by fdsa1538** [comment]
DIBE 못써서 아쉽네요.. 어디아이피인지 심지어 어디대학인지도 알려주고 고정닉 아이디 뭔지 옆에 표시되는거 좋은데 koolside랑 같이 쓰면 DIBE가 기능을 못해요
해결되어서 닫는데 미리보기에 커서 가져다대면 글 목록 옆으로 움직이는것도 고쳐주실 수 있나요 
미리보기에 커서 올리고 내리고 반복하면 지진난거 같이 흔들려요
