### ISSUE TITLE
실행 시 나오는 에러코드 

### ISSUE THREAD

**Issue by DCPCGALL** [koolside/koolside#30]
다운을 하고 실행시키면 다음과 같은 에러나옴
![1](https://user-images.githubusercontent.com/64078880/79862037-64943880-8410-11ea-9d02-d02d1e06fce1.JPG)
프로그램 자체에 문제인지 내 컴퓨터의 문제인지는 모르겠지만
해결 방법좀ㅇㅇ

**Comment by toriato** [comment]
브라우저 별로 유저스크립트 확장기능 설치 후 누르셔야 설치가 진행됩니다.

### 크롬
https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag

### 파이어폭스
https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/

**Comment by DCPCGALL** [comment]
감사

> 브라우저 별로 유저스크립트 확장기능 설치 후 누르셔야 설치가 진행됩니다.
> 
> ### 크롬
> https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag
> 
> ### 파이어폭스
> https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/

ㄱㅅㄱㅅ

**Comment by DCPCGALL** [comment]
ㄱㅅ
